<%@ Page Language="C#" AutoEventWireup="true" CodeFile="ASP Items.aspx.cs" Inherits="ASP_Items" %>

<!-- 
This ASPX was generated by a purpose built internal Monday 9AM Ensemble development utility.
The HTML content was generated by bootstrap studio.

It looks dreadful in the Visual Studio preview, but fine when hosted in a browser.
The bootstrap front end seems perfectly compatable.
-->


<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>LS Goods - Jordan</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/styles.css">
</head>

<body>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>