<%@ Page Language="C#" AutoEventWireup="true" CodeFile="OrderConfirmDelete.aspx.cs" Inherits="OrderConfirmDelete" %>

<!-- 
This ASPX was generated by a purpose built internal Monday 9AM Ensemble development utility.
The HTML content was generated by bootstrap studio.

It looks dreadful in the Visual Studio preview, but fine when hosted in a browser.
The bootstrap front end seems perfectly compatable.
-->


<!DOCTYPE html>
<html style="height: 100%;width: 100%;">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>LS Goods - Jordan</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="assets/css/-Login-form-Page-BS4-.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="assets/css/styles.css">
</head>

<body style="height: 100%;width: 100%;min-height: 100%;">
    <div class="container-fluid">
        <div class="row mh-100vh">
            <div class="col-10 col-sm-8 col-md-6 col-lg-6 offset-1 offset-sm-2 offset-md-3 offset-lg-0 align-self-center d-lg-flex align-items-lg-center align-self-lg-stretch jello animated infinite bg-white p-5 rounded rounded-lg-0 my-5 my-lg-0" id="login-block">
                <div class="m-auto swing animated infinite w-lg-75 w-xl-50">
                    <h2 class="text-info font-weight-light mb-5"><i class="fa fa-diamond"></i>&nbsp;LS Wholesaler</h2>
                    <form method="post" runat="server">
                        <div class="form-group shake animated infinite"><asp:Label ID="lblmsg" runat="server" Text="Don't you not want to discard this order, or not?"></asp:Label></div>
                        <div class="d-xl-flex flex-row flex-grow-1 flex-fill justify-content-xl-center align-items-xl-center">
                            <div class="d-xl-flex flex-row flex-fill justify-content-xl-center flash animated infinite" style="background: #ea4848;padding: 5px;"><i class="fa fa-warning d-xl-flex align-items-xl-center" style="border-color: rgb(39,71,103);color: rgb(255,214,0);"></i><asp:Button ID="btnYes" runat="server" Text="Of course!"  OnClick="btnYes_Click"></asp:Button><i class="fa fa-warning d-xl-flex align-items-xl-center" style="border-color: rgb(39,71,103);color: rgb(255,214,0);"></i></div>
                            <div class="d-xl-flex flex-row flex-fill justify-content-xl-center align-items-xl-center tada animated infinite" style="background: #61ff00;padding: 5px;"><asp:Button ID="btnNo" runat="server" Text="Absolutely not"  OnClick="btnNo_Click"></asp:Button></div>
                        </div>
                    </form><a class="pulse animated infinite text-info small" href="https://www.timetothink.com">Think of the environment :(</a>
                    <div class="tada animated infinite"><asp:Label ID="lbldisclamer" runat="server" Text="Disclamer; Approx 6 cats will be harmed whilst discarding an order"></asp:Label></div>
                </div>
            </div>
            <div class="col-lg-6 d-flex align-items-end jello animated infinite" id="bg-block" style="background: url(&quot;assets/img/landfill.jpeg&quot;) center center / cover no-repeat;">
                <p class="ml-auto small text-dark mb-2"><em>Photo by&nbsp;</em><a class="text-dark" href="https://unsplash.com/photos/v0zVmWULYTg?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText" target="_blank"><em>Aldain Austria</em></a><br></p>
            </div>
        </div>
    </div>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>